
title: Essentials Plugin Library
description: A currated list of available essentials plugins [EPI]


remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
